name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31

    - name: Build
      run: nix-shell --run "cargo build --verbose --release"

    - name: Run tests
      run: nix-shell --run "cargo test --verbose --release"

    - name: check formatting
      run: nix-shell --run "cargo fmt --check"
